version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4040:4040'
    env_file:
      - ./.env/backend.env
  frontend:
    build: ./frontend
    ports:
      - '80:8000'
    depends_on:
      - backend
volumes:
  data:
